# Generated by Django 4.2.23 on 2025-07-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lookup_key', models.SlugField(help_text="A unique, code-friendly key to look up this prompt (e.g., 'single-prompt').", max_length=100, unique=True)),
                ('prompt_template', models.TextField(help_text='The prompt content. Use {{ <var-name> }} for Django context. Use { <var-name> } for lang chain context.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
            },
        ),
    ]
