# Generated by Django 4.2.23 on 2025-07-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_created_PromptTemplate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('term', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='A list of synonym strings(words).')),
            ],
            options={
                'verbose_name': 'Dictionary Word',
                'verbose_name_plural': 'Dictionary Words',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryWordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='chat_bot.dictionaryword')),
            ],
            options={
                'verbose_name': 'Dictionary Meaning',
                'verbose_name_plural': 'Dictionary Meanings',
            },
        ),
    ]
