# Generated by Django 4.2.23 on 2025-07-25 04:05
# NOTE: Manually created migration to enable the pgvector extension in PostgreSQL.

from django.db import migrations

from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_created_dictionary_models'),
    ]

    operations = [
        VectorExtension()
    ]
