# Generated by Django 4.2.23 on 2025-07-25 04:44

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_enable_pgvector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryword',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
