# Generated by Django 4.2.23 on 2025-08-06 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_bot', '0004_DictionaryWord_added_vector_embedding_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('recurrence_rule', models.TextField(blank=True, help_text='RRULE for recurring events')),
                ('recurrence_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('combined_text', models.TextField(blank=True, help_text='Combined text for embedding generation')),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('raw_google_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CalendarRAGQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('include_attachments', models.BooleanField(default=True)),
                ('date_range_days', models.IntegerField(blank=True, null=True)),
                ('events_found', models.IntegerField(default=0)),
                ('similarity_threshold', models.FloatField(default=0.7)),
                ('similarity_scores', models.JSONField(blank=True, default=dict, help_text='Event IDs mapped to similarity scores')),
                ('generated_response', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='User rating from 1-5', null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retrieved_events', models.ManyToManyField(blank=True, related_name='rag_queries', to='chat_bot.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG Query',
                'verbose_name_plural': 'RAG Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chat_bot_ca_user_id_bbd435_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('icon_link', models.URLField(blank=True)),
                ('raw_content', models.TextField(blank=True, help_text='Raw extracted text content')),
                ('processed_content', models.TextField(blank=True, help_text='Cleaned and processed content')),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('extraction_method', models.CharField(blank=True, help_text='Method used to extract text (pdf, docx, etc.)', max_length=50)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('unsupported', 'Unsupported Format')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_bot.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Event Attachment',
                'verbose_name_plural': 'Calendar Event Attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'processing_status'], name='chat_bot_ca_event_i_8f6a8e_idx'), models.Index(fields=['file_id'], name='chat_bot_ca_file_id_3650ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_datetime'], name='chat_bot_ca_user_id_a09850_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['google_event_id'], name='chat_bot_ca_google__f0818f_idx'),
        ),
    ]
